### ISSUE TITLE
robust_physical_attack.ipynb to robust-physical-attack.py

### ISSUE THREAD

**Issue by gmt710** [shangtse/robust-physical-attack#2]
I copy robust_physical_attack.ipynb to robust-physical-attack.py,run this program and get this error:
OSError: [Errno 99] Cannot assign requested address.
I don't know exactly why.

**Comment by shangtse** [comment]
What do you mean you copy robust_physical_attack.ipynb to robust-physical-attack.py?
*.ipynb is an IPython notebook file, and it won't work if you directly change it to a pure python file.
You can open it with IPython notebook and export it as a python file if you want.

**Comment by gmt710** [comment]
yes, I converted *.ipynb file to *.py file via jupyter notebook.run the program in Pycharm,and get the error.

**Comment by gmt710** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1698, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.5/urllib/request.py", line 1877, in open_http
    return self._open_generic_http(http.client.HTTPConnection, url, data)
  File "/usr/lib/python3.5/urllib/request.py", line 1857, in _open_generic_http
    http_conn.request("GET", selector, headers=headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
​
During handling of the above exception, another exception occurred:
​
Traceback (most recent call last):
  File "/home/g1065504814/ubuntu/robust-physical-attack-master/robust_physical_attack.py", line 52, in <module>
    opener.retrieve(DOWNLOAD_BASE + MODEL_FILE, MODEL_FILE)
  File "/usr/lib/python3.5/urllib/request.py", line 1732, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python3.5/urllib/request.py", line 1704, in open
    raise OSError('socket error', msg).with_traceback(sys.exc_info()[2])
  File "/usr/lib/python3.5/urllib/request.py", line 1698, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.5/urllib/request.py", line 1877, in open_http
    return self._open_generic_http(http.client.HTTPConnection, url, data)
  File "/usr/lib/python3.5/urllib/request.py", line 1857, in _open_generic_http
    http_conn.request("GET", selector, headers=headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
OSError: [Errno socket error] [Errno 99] Cannot assign requested address

**Comment by gmt710** [comment]
It may be that sometimes I cannot access the website of tensorflow. I have solved this problem, thank you.I download the model,and modify
opener = urllib.request.URLopener()                         
opener.retrieve(DOWNLOAD_BASE + MODEL_FILE, MODEL_FILE)  
to
if not os.path.exists(MODEL_FILE):                              
    opener = urllib.request.URLopener()                         
    opener.retrieve(DOWNLOAD_BASE + MODEL_FILE, MODEL_FILE)
